In [0]:
import numpy as np

In [0]:
def pool_forward(A_prev,hyper_parameters):
  (m,n_H_prev,n_W_prev,n_C_prev)=np.shape(A_prev)

  print("\nNumber of training examples = ",m)
  print("\nHeight dimension of output of previous layer =",n_H_prev)
  print("\nWidth  dimension of output of previous layer =",n_W_prev)
  print("\nNumber of channels in the  output of previous layer =",n_C_prev)

  f = hyper_parameters["f"]
  stride = hyper_parameters["stride"]

  print("\nHeight dimension of filter kernel =",f)
  print("\nWidth  dimension of filter kernel =",f)
  print("\nNumber of steps used by filter to move or parse across the output of previous layer =",stride)

  print("\nComputing the height and width dimension of the output using formulas:-\n\n") 
  print("\n       |    n_H_prev - f      |                |    n_W_prev - f      |")    
  print("\n n_H = |----------------------| + 1     n_W =  |----------------------| + 1")
  print("\n       |       stride         |                |       stride         |")

  n_H = int(1+(n_H_prev-f)/stride)
  n_W = int(1+(n_W_prev-f)/stride)
  n_C = n_C_prev

  print("\nHeight dimension of the result = ",n_H) 
  print("\nWidth  dimension of the result = ",n_W)

  A = np.zeros((m,n_H,n_W,n_C))

  print("\n Applying Max pooling filters on the input data .........")
  for i in range(m):
    
    for h in range(n_H):
      vert_start = h*stride
      vert_end   = h*stride + f

      for w in range(n_W):
        horiz_start = w*stride
        horiz_end   = w*stride + f

        for c in range(n_C):
          a_prev_slice = A_prev[i,vert_start:vert_end,horiz_start:horiz_end,c]

          A[i,h,w,c] = np.max(a_prev_slice)

  cache = (A_prev,hyper_parameters)
  assert(A.shape == (m,n_H,n_W,n_C))  
  return A,cache      

In [3]:
np.random.seed(1)
A_prev = np.random.randn(2,5,5,3)
hyper_parameters = {"stride":1,"f":3}

A,cache = pool_forward(A_prev,hyper_parameters)
print("\n Max pooling")
print("\n Dimensions after applying Max pooling = "+str(A.shape))
print("\n A= \n",A)


Number of training examples =  2

Height dimension of output of previous layer = 5

Width  dimension of output of previous layer = 5

Number of channels in the  output of previous layer = 3

Height dimension of filter kernel = 3

Width  dimension of filter kernel = 3

Number of steps used by filter to move or parse across the output of previous layer = 1

Computing the height and width dimension of the output using formulas:-



       |    n_H_prev - f      |                |    n_W_prev - f      |

 n_H = |----------------------| + 1     n_W =  |----------------------| + 1

       |       stride         |                |       stride         |

Height dimension of the result =  3

Width  dimension of the result =  3

 Applying Max pooling filters on the input data .........

 Max pooling

 Dimensions after applying Max pooling = (2, 3, 3, 3)

 A= 
 [[[[1.74481176 0.90159072 1.65980218]
   [1.74481176 1.46210794 1.65980218]
   [1.74481176 1.6924546  1.65980218]]

  [[1.14472371 0.90